### ISSUE TITLE
gitlab-ci: Use CI_PROJECT_PATH_SLUG in docker image name

### ISSUE THREAD

**Issue by NGenetzky** [hassio-addons/organization#4]
This actually caused me quite a bit of headache today, and so I figured I would get a bug report filed and a fix put together.

Example:

```
$ docker build \ # collapsed multi-line command
invalid argument "registry.gitlab.com/NGenetzky/ngenetzky-hassio-common/amd64:523358a25161ce45f8566a47453a3b034c9275a7" for "-t, --tag" flag: invalid reference format: repository name must be lowercase
See 'docker build --help'.
```

One or more of the following links should point to the job referenced above (see if you can spot the difference).

- https://gitlab.com/NGenetzky/ngenetzky-hassio-common/-/jobs/565543598
- https://gitlab.com/genetzky/ngenetzky-hassio-common/-/jobs/565543598
- https://gitlab.com/ngenetzky/ngenetzky-hassio-common/-/jobs/565543598

<blockquote><img src="https://assets.gitlab-static.net/assets/gitlab_logo-7ae504fe4f68fdebb3c2034e36621930cd36ea87924c11ff65dbcb8ed50dca58.png" width="48" align="right"><div>GitLab</div><div><strong><a href="https://gitlab.com/genetzky/ngenetzky-hassio-common/-/jobs/565543598">build:amd64 (#565543598) · Jobs · Nathan Genetzky / ngenetzky-hassio-common</a></strong></div><div>git submodule repository of building blocks in my Hass.io setup</div></blockquote>
<blockquote><img src="https://assets.gitlab-static.net/assets/gitlab_logo-7ae504fe4f68fdebb3c2034e36621930cd36ea87924c11ff65dbcb8ed50dca58.png" width="48" align="right"><div>GitLab</div><div><strong><a href="https://gitlab.com/genetzky/ngenetzky-hassio-common/-/jobs/565543598">build:amd64 (#565543598) · Jobs · Nathan Genetzky / ngenetzky-hassio-common</a></strong></div><div>git submodule repository of building blocks in my Hass.io setup</div></blockquote>
<blockquote><img src="https://assets.gitlab-static.net/assets/gitlab_logo-7ae504fe4f68fdebb3c2034e36621930cd36ea87924c11ff65dbcb8ed50dca58.png" width="48" align="right"><div>GitLab</div><div><strong><a href="https://gitlab.com/genetzky/ngenetzky-hassio-common/-/jobs/565543598">build:amd64 (#565543598) · Jobs · Nathan Genetzky / ngenetzky-hassio-common</a></strong></div><div>git submodule repository of building blocks in my Hass.io setup</div></blockquote>

**Comment by frenck** [comment]
Interesting makes kinda sense 👍 

However, not going to change it for the add-on project. As there is no need to do that for us.

Furthermore, one of my main goals right now is to say goodbye to GitLab. They have served me well, but they still suck.
